import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import YAML from 'yaml';
import {pageSchema} from '../src/lib/content-schema.ts';
const home=JSON.parse(readFileSync('src/content/pages/home.json','utf8'));
test('optional semantic motif caption survives CMS parsing and preserves independent artwork/crop fields',()=>{
  const fixture=structuredClone(home), item=fixture.homepage.packages.items[0];
  item.visualCaption={label:'CMS label',support:'CMS support'};
  item.visualAsset={src:'/images/pricing/alternative.svg',alt:'Conceptual option',positionX:20,positionY:80};
  const parsed=pageSchema.parse(fixture).homepage!.packages.items[0];
  assert.deepEqual(parsed.visualCaption,item.visualCaption);
  assert.deepEqual(parsed.visualAsset,item.visualAsset);
  item.visualCaption={label:'CMS label'};
  assert.equal(pageSchema.parse(fixture).homepage!.packages.items[0].visualCaption?.support,undefined);
  item.visualCaption={label:' '};assert.equal(pageSchema.safeParse(fixture).success,false);
  delete item.visualCaption;assert.equal(pageSchema.safeParse(fixture).success,true);
  const cms=YAML.parse(readFileSync('../.pages.yml','utf8'));
  const fields=cms.content.find((c:any)=>c.name==='homepage').fields.find((f:any)=>f.name==='homepage').fields.find((f:any)=>f.name==='packages').fields.find((f:any)=>f.name==='items').fields;
  assert.deepEqual(fields.find((f:any)=>f.name==='visualCaption').fields.map((f:any)=>f.name),['label','support']);
  assert.deepEqual(fields.find((f:any)=>f.name==='visualAsset').fields.map((f:any)=>f.name),['src','alt','positionX','positionY']);
});
